name: PR validation

on:
  push:
    branches:
      - main
jobs:
  validation:
    name: Tests
    runs-on: ubuntu
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Typescript check
        run: npm run typescript

      - name: Tests
        run: npm run test
