name: Tests

on:
  push:
    branches:
      - main
jobs:
  validation:
    name: Main branch check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test
